// Lista de trabajos — debe coincidir EXACTAMENTE entre elegir.js y work.js
export const TRABAJOS = [
  {
    id: 'programador',
    nombre: 'Programador',
    emoji: '💻',
    tareas: [
      '💻 Hackeaste la red de una empresa y ganaste',
      '🖥️ Arreglaste un bug crítico en producción y obtuviste',
      '⌨️ Programaste una app para un cliente y recibiste',
      '🐛 Pasaste la noche depurando código y ganaste',
      '🌐 Creaste un sitio web y obtuviste',
      '🗄️ Optimizaste una base de datos y recibiste',
      '🤖 Desarrollaste una IA para un cliente y ganaste',
      '☁️ Configuraste un servidor en la nube y obtuviste',
      '🏆 Ganaste un hackathon y recibiste',
      '⚙️ Automatizaste un proceso con un script y ganaste',
    ],
  },
  {
    id: 'policia',
    nombre: 'Policía',
    emoji: '👮',
    tareas: [
      '🚔 Atrapaste a un ladrón y ganaste',
      '🚨 Resolviste un caso importante y obtuviste',
      '🛑 Multaste a varios infractores y recibiste',
      '🕵️ Investigaste una pista clave y ganaste',
      '👮 Patrullaste la ciudad toda la noche y obtuviste',
      '🚓 Desarticulaste una banda criminal y recibiste',
      '🛡️ Escoltaste a un VIP y ganaste',
      '🚗 Recuperaste un vehículo robado y obtuviste',
      '🔍 Capturaste a un fugitivo y recibiste',
      '📢 Controlaste un disturbio y ganaste',
    ],
  },
  {
    id: 'doctor',
    nombre: 'Doctor',
    emoji: '🩺',
    tareas: [
      '🩺 Salvaste una vida en cirugía y ganaste',
      '💉 Vacunaste a todo un barrio y obtuviste',
      '🏥 Atendiste emergencias toda la noche y recibiste',
      '🦴 Curaste una fractura complicada y ganaste',
      '🧬 Diagnosticaste un caso difícil y obtuviste',
      '❤️ Realizaste un trasplante exitoso y recibiste',
      '👶 Atendiste un parto complicado y ganaste',
      '🔬 Descubriste una enfermedad rara a tiempo y obtuviste',
      '🏠 Diste consulta a domicilio y recibiste',
      '💓 Trataste una emergencia cardíaca y ganaste',
    ],
  },
  {
    id: 'chef',
    nombre: 'Chef',
    emoji: '👨‍🍳',
    tareas: [
      '👨‍🍳 Cocinaste en un restaurante 5 estrellas y ganaste',
      '🍰 Horneaste postres deliciosos y obtuviste',
      '🍜 Preparaste un banquete completo y recibiste',
      '🔪 Ganaste un concurso de cocina y ganaste',
      '🍽️ Atendiste una gran cena de gala y obtuviste',
      '📋 Creaste un plato nuevo en el menú y recibiste',
      '💍 Cateraste una boda y ganaste',
      '⭐ Impresionaste a un crítico gastronómico y obtuviste',
      '🏢 Preparaste comida para un evento corporativo y recibiste',
      '📚 Enseñaste una clase de cocina y ganaste',
    ],
  },
  {
    id: 'mecanico',
    nombre: 'Mecánico',
    emoji: '🔧',
    tareas: [
      '🔧 Reparaste un motor y ganaste',
      '🛠️ Arreglaste un auto de carreras y obtuviste',
      '🚗 Cambiaste piezas de un vehículo y recibiste',
      '⚙️ Solucionaste una falla eléctrica y ganaste',
      '🏁 Preparaste un auto para una carrera y obtuviste',
      '🚙 Restauraste un auto clásico y recibiste',
      '🛢️ Hiciste un cambio de aceite express y ganaste',
      '⚡ Reparaste una transmisión dañada y obtuviste',
      '🏍️ Ajustaste el motor de una moto y recibiste',
      '🛣️ Solucionaste una avería en carretera y ganaste',
    ],
  },
  {
    id: 'piloto',
    nombre: 'Piloto',
    emoji: '✈️',
    tareas: [
      '✈️ Volaste un avión comercial y ganaste',
      '🛫 Completaste un vuelo internacional y obtuviste',
      '🗺️ Aterrizaste con éxito en condiciones difíciles y recibiste',
      '🎫 Transportaste pasajeros VIP y ganaste',
      '🌍 Sobrevolaste el océano y obtuviste',
      '🚁 Pilotaste un vuelo de emergencia y recibiste',
      '👨‍✈️ Entrenaste a un copiloto nuevo y ganaste',
      '🛩️ Volaste un jet privado y obtuviste',
      '📦 Completaste una ruta de carga y recibiste',
      '⛈️ Evitaste una tormenta en pleno vuelo y ganaste',
    ],
  },
  {
    id: 'youtuber',
    nombre: 'Youtuber',
    emoji: '🎥',
    tareas: [
      '🎥 Subiste un video viral y ganaste',
      '📈 Conseguiste miles de suscriptores nuevos y obtuviste',
      '🎬 Grabaste un video patrocinado y recibiste',
      '🔴 Hiciste un directo exitoso y ganaste',
      '💬 Tu video llegó a tendencias y obtuviste',
      '🤝 Colaboraste con otro creador y recibiste',
      '🥈 Ganaste un botón de plata y ganaste',
      '✂️ Editaste un video toda la noche y obtuviste',
      '💡 Se te ocurrió una idea viral y recibiste',
      '👕 Lanzaste tu propio merch y ganaste',
    ],
  },
  {
    id: 'abogado',
    nombre: 'Abogado',
    emoji: '⚖️',
    tareas: [
      '⚖️ Ganaste un juicio importante y ganaste',
      '📜 Redactaste un contrato millonario y obtuviste',
      '🏛️ Defendiste un caso difícil en la corte y recibiste',
      '🗂️ Asesoraste a un cliente importante y ganaste',
      '👨‍⚖️ Convenciste al juez con tu alegato y obtuviste',
      '🤝 Negociaste un acuerdo extrajudicial y recibiste',
      '📈 Ganaste una apelación complicada y ganaste',
      '🏢 Representaste a una empresa en un litigio y obtuviste',
      '🌎 Revisaste un contrato internacional y recibiste',
      '❤️ Defendiste un caso pro bono y ganaste',
    ],
  },
  {
    id: 'bombero',
    nombre: 'Bombero',
    emoji: '🚒',
    tareas: [
      '🚒 Apagaste un incendio a tiempo y ganaste',
      '🔥 Rescataste a una familia atrapada y obtuviste',
      '🐱 Rescataste a un gato de un árbol y recibiste',
      '🧯 Controlaste una emergencia peligrosa y ganaste',
      '🚨 Respondiste a una llamada de emergencia y obtuviste',
      '🏢 Evacuaste un edificio en llamas y recibiste',
      '🚑 Rescataste a alguien de un accidente de auto y ganaste',
      '🌲 Contuviste un incendio forestal y obtuviste',
      '🎓 Capacitaste a nuevos bomberos y recibiste',
      '🌊 Salvaste a una mascota de una inundación y ganaste',
    ],
  },
  {
    id: 'cientifico',
    nombre: 'Científico',
    emoji: '🧪',
    tareas: [
      '🧪 Descubriste una nueva fórmula y ganaste',
      '🔬 Publicaste una investigación importante y obtuviste',
      '🧫 Hiciste un experimento exitoso y recibiste',
      '🚀 Contribuiste a un proyecto espacial y ganaste',
      '🌡️ Resolviste un problema científico complejo y obtuviste',
      '💊 Desarrollaste una vacuna experimental y recibiste',
      '🦋 Descubriste una nueva especie y ganaste',
      '🎤 Presentaste tu investigación en una conferencia y obtuviste',
      '📄 Patentaste un invento y recibiste',
      '🔎 Analizaste muestras en el laboratorio y ganaste',
    ],
  },
]
